/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frm;

import KFC.Main;
import static KFC.Main.frmTC;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class NCCJPanel extends javax.swing.JPanel {

    /** Creates new form NCCJPanel */
    public NCCJPanel() {
        initComponents();
        LayDuLieuNCC();
    }
 public void LayDuLieuNCC(){
    String cautruyvan = "";
        cautruyvan = "select * from NHACUNGCAP ";
        ResultSet rs = Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"STT", "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ nhà cung cấp","Điện Thoại","Web"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblNCC.setModel(tableModel);
        int c = 0;
        try {
            while (rs.next()) {
                Object[] item = new Object[6];
                c++;
                item[0] = c;
                item[1] = rs.getString("MANCC");
                item[2] = rs.getString("TENNCC");
                item[3] = rs.getString("DIACHINCC");
                item[4] = rs.getString("DIENTHOAIKH");
               
                item[5] = rs.getString("WEB");
                
            
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
 }
  public boolean KiemTraNhapNCC(int ts) {
        boolean kiemtra = false;
         String MaNCC,TenNCC,DiaChiNCC,DienThoaiNCC,Web;
        MaNCC=txtMaNCC.getText();
        TenNCC=txtTenNCC.getText();
        DiaChiNCC=txtDiaChiNCC.getText();
        DienThoaiNCC=txtDienThoaiNCC.getText();
        Web=txtWebNCC.getText();
     
        String  ThongBao = "";
        
        if (MaNCC.equals("") && ts == 1) {
            ThongBao += "Bạn Chưa nhập mã nhà cung cấp\n";
            lblMaNCC.setForeground(Color.red);
        }
        if (TenNCC.equals("")) {
            ThongBao += "Bạn chưa nhập tên nhà cung cấp\n";
            lblTenNCC.setForeground(Color.red);
            
        }
        if (DienThoaiNCC.equals("")) {
            ThongBao += "Bạn chưa nhập điện thoại nhà cung cấp\n";
            lblDienThoaiNCC.setForeground(Color.red);
        }
        if (DiaChiNCC.equals("")) {
            lblDiaChiNCC.setForeground(Color.red);
            ThongBao += "Bạn chưa nhập địa chỉ nhà cung cấp\n";
        }
        if (Web.equals("")) {
            lblWeb.setForeground(Color.red);
            ThongBao += "Bạn chưa nhập địa chỉ web \n";
           
        }
        
        if (ThongBao.equals("")) {
            kiemtra = true;
            lblMaNCC.setForeground(Color.black);
            lblTenNCC.setForeground(Color.black);
            lblDienThoaiNCC.setForeground(Color.black);
            lblDiaChiNCC.setForeground(Color.black);
            lblWeb.setForeground(Color.black);
           
        } else {
            kiemtra = false;
            frmTC.ThongBao(ThongBao, "LỖI NHẬP LIỆU", 2);
        }
        return kiemtra;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNCC = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblMaNCC = new javax.swing.JLabel();
        lblTenNCC = new javax.swing.JLabel();
        lblDiaChiNCC = new javax.swing.JLabel();
        lblDienThoaiNCC = new javax.swing.JLabel();
        lblWeb = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        txtTenNCC = new javax.swing.JTextField();
        txtDiaChiNCC = new javax.swing.JTextField();
        txtDienThoaiNCC = new javax.swing.JTextField();
        txtWebNCC = new javax.swing.JTextField();
        btnThemNCC = new javax.swing.JButton();
        btnXoaNCC = new javax.swing.JButton();
        btnSuaNCC = new javax.swing.JButton();
        btnResetNCC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RadMaNCC = new javax.swing.JRadioButton();
        RadTenNCC = new javax.swing.JRadioButton();
        txtTimNCC = new javax.swing.JTextField();
        btnTimNCC = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("NHÀ CUNG CẤP");

        tblNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhà cung câp", "Tên nhà cung cấp", "Địa chỉ NCC", "Điện thoại", "Web"
            }
        ));
        tblNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNCC);

        lblMaNCC.setText("Mã nhà cung cấp");

        lblTenNCC.setText("Tên nhà cung cấp");

        lblDiaChiNCC.setText("Địa chỉ ");

        lblDienThoaiNCC.setText("Điện thoại");

        lblWeb.setText("Web");

        btnThemNCC.setText("Thêm");
        btnThemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNCCActionPerformed(evt);
            }
        });

        btnXoaNCC.setText("Xóa");
        btnXoaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNCCActionPerformed(evt);
            }
        });

        btnSuaNCC.setText("Sửa");
        btnSuaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNCCActionPerformed(evt);
            }
        });

        btnResetNCC.setText("Reset");
        btnResetNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTenNCC)
                                .addComponent(lblMaNCC))
                            .addComponent(lblDiaChiNCC))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNCC)
                            .addComponent(txtTenNCC)
                            .addComponent(txtDiaChiNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDienThoaiNCC)
                            .addComponent(lblWeb))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDienThoaiNCC)
                            .addComponent(txtWebNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemNCC)
                        .addGap(93, 93, 93)
                        .addComponent(btnSuaNCC)
                        .addGap(92, 92, 92)
                        .addComponent(btnXoaNCC)
                        .addGap(134, 134, 134)
                        .addComponent(btnResetNCC)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNCC)
                    .addComponent(lblDienThoaiNCC)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDienThoaiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNCC)
                    .addComponent(lblWeb)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWebNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChiNCC)
                    .addComponent(txtDiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNCC)
                    .addComponent(btnSuaNCC)
                    .addComponent(btnResetNCC)
                    .addComponent(btnXoaNCC))
                .addGap(25, 25, 25))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Tìm Kiếm");

        RadMaNCC.setText("Mã nhà cung cấp");

        RadTenNCC.setText("Tên nhà cung cấp");

        btnTimNCC.setText("Tìm");
        btnTimNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RadMaNCC))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RadTenNCC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTimNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTimNCC)
                        .addGap(70, 70, 70))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(RadMaNCC)
                .addGap(18, 18, 18)
                .addComponent(RadTenNCC)
                .addGap(18, 18, 18)
                .addComponent(txtTimNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimNCC)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(587, 587, 587))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNCCActionPerformed
        // TODO add your handling code here:
          String MaNCC,TenNCC,DiaChiNCC,DienThoaiNCC,Web;
        MaNCC=txtMaNCC.getText();
        TenNCC=txtTenNCC.getText();
        DiaChiNCC=txtDiaChiNCC.getText();
        DienThoaiNCC=txtDienThoaiNCC.getText();
        Web=txtWebNCC.getText();
          String cautruyvan = "INSERT into NHACUNGCAP(MANCC,TENNCC,DIACHINCC,DIENTHOAIKH,WEB) Values('" + MaNCC + "',N'" + TenNCC + "',N'" + DiaChiNCC + "','" + DienThoaiNCC + "','" + Web + "')";
        
        boolean kiemtra = KiemTraNhapNCC(0);
        if (kiemtra) {
            Main.connection.ExcuteQueryUpdateDB(cautruyvan);
            Main.frmTC.infoBox("Thêm Thành Công !!!", "Thông báo");
            System.out.println("Đã Thêm Thành Công");
            System.out.println(cautruyvan);
        } else {
            System.out.println("Thất Bại");
        }
        LayDuLieuNCC();
    }//GEN-LAST:event_btnThemNCCActionPerformed

    private void btnXoaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNCCActionPerformed
        // TODO add your handling code here:
         String MaNCC= txtMaNCC.getText();
        String cautruyvan = "delete NHACUNGCAP where MANCC='" + MaNCC+"';";
         Main.frmTC.infoBox("Lỗi Xóa nhà cung cấp !!!", "Thông báo");
         boolean kiemtra = KiemTraNhapNCC(0);
        if (kiemtra) {
            Main.connection.ExcuteQueryUpdateDB(cautruyvan);
            System.out.println("Đã Xóa Thành Công");
            Main.frmTC.infoBox("Xóa Thành Công !!!", "Thông báo");
            System.out.println(cautruyvan);
        } else {
            System.out.println("Thất Bại");
        }
        LayDuLieuNCC();
    }//GEN-LAST:event_btnXoaNCCActionPerformed

    private void btnSuaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNCCActionPerformed
        // TODO add your handling code here:
          String MaNCC,TenNCC,DiaChiNCC,DienThoaiNCC,Web;
        MaNCC=txtMaNCC.getText();
        TenNCC=txtTenNCC.getText();
        DiaChiNCC=txtDiaChiNCC.getText();
        DienThoaiNCC=txtDienThoaiNCC.getText();
        Web=txtWebNCC.getText();
         String cautruyvan = "Update NHACUNGCAP set TENNCC= N'" + TenNCC + "',DIACHINCC=N'" + DiaChiNCC + "',DIENTHOAIKH='" + DienThoaiNCC + "',WEB='" + Web + "'WHERE MANCC='" + MaNCC + "';";;
        
        boolean kiemtra = KiemTraNhapNCC(0);
        if (kiemtra) {
            Main.connection.ExcuteQueryUpdateDB(cautruyvan);
            Main.frmTC.infoBox("Sửa Thành Công !!!", "Thông báo");
            System.out.println("Đã Sửa Thành Công");
            System.out.println(cautruyvan);
        } else {
            System.out.println("Thất Bại");
        }
        LayDuLieuNCC();
    }//GEN-LAST:event_btnSuaNCCActionPerformed

    private void btnResetNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetNCCActionPerformed
        // TODO add your handling code here:
        txtMaNCC.setText("");
        txtTenNCC.setText("");
        txtDiaChiNCC.setText("");
        txtDienThoaiNCC.setText("");
        txtWebNCC.setText("");
        LayDuLieuNCC();
          Main.frmTC.infoBox("Reset Thành Công !!!", "Thông báo");
    }//GEN-LAST:event_btnResetNCCActionPerformed

    private void tblNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNCCMouseClicked
        // TODO add your handling code here:
         int viTriDongVuaBam = tblNCC.getSelectedRow();
        txtMaNCC.setText(tblNCC.getValueAt(viTriDongVuaBam, 1).toString());
        txtTenNCC.setText(tblNCC.getValueAt(viTriDongVuaBam, 2).toString());
        txtDiaChiNCC.setText(tblNCC.getValueAt(viTriDongVuaBam, 3).toString());
        txtDienThoaiNCC.setText(tblNCC.getValueAt(viTriDongVuaBam, 4).toString());
        txtWebNCC.setText(tblNCC.getValueAt(viTriDongVuaBam, 5).toString());
    }//GEN-LAST:event_tblNCCMouseClicked

    private void btnTimNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimNCCActionPerformed
        // TODO add your handling code here:
        if (RadMaNCC.isSelected())
        {
             String cautruyvan="Select * from NHACUNGCAP where MANCC='"+txtTimNCC.getText()+"'" ;
             ResultSet rs = Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"STT", "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ nhà cung cấp","Điện Thoại","Web"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblNCC.setModel(tableModel);
        int c = 0;
        try {
            while (rs.next()) {
                Object[] item = new Object[6];
                c++;
                item[0] = c;
                item[1] = rs.getString("MANCC");
                item[2] = rs.getString("TENNCC");
                item[3] = rs.getString("DIACHINCC");
                item[4] = rs.getString("DIENTHOAIKH");
               
                item[5] = rs.getString("WEB");
                
            
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        } else if (RadTenNCC.isSelected())
        {
            String cautruyvan  = "select * from NHACUNGCAP where TENNCC like N'"+txtTimNCC.getText().trim()+"'";
            ResultSet rs = Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"STT", "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ nhà cung cấp","Điện Thoại","Web"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblNCC.setModel(tableModel);
        int c = 0;
        try {
            while (rs.next()) {
                Object[] item = new Object[6];
                c++;
                item[0] = c;
                item[1] = rs.getString("MANCC");
                item[2] = rs.getString("TENNCC");
                item[3] = rs.getString("DIACHINCC");
                item[4] = rs.getString("DIENTHOAIKH");
               
                item[5] = rs.getString("WEB");
                
            
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        }
    }//GEN-LAST:event_btnTimNCCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadMaNCC;
    private javax.swing.JRadioButton RadTenNCC;
    private javax.swing.JButton btnResetNCC;
    private javax.swing.JButton btnSuaNCC;
    private javax.swing.JButton btnThemNCC;
    private javax.swing.JButton btnTimNCC;
    private javax.swing.JButton btnXoaNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiaChiNCC;
    private javax.swing.JLabel lblDienThoaiNCC;
    private javax.swing.JLabel lblMaNCC;
    private javax.swing.JLabel lblTenNCC;
    private javax.swing.JLabel lblWeb;
    private javax.swing.JTable tblNCC;
    private javax.swing.JTextField txtDiaChiNCC;
    private javax.swing.JTextField txtDienThoaiNCC;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtTenNCC;
    private javax.swing.JTextField txtTimNCC;
    private javax.swing.JTextField txtWebNCC;
    // End of variables declaration//GEN-END:variables

}
