/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import KFC.Main;
import static KFC.Main.frmTC;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class NhanVienJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhanVienJPanel
     */
    public NhanVienJPanel() {
        initComponents();
        LaydulieuNhanVien();
    }
 public void LaydulieuNhanVien(){
    String cautruyvan = "";
        cautruyvan = "select * from NHANVIEN ";
        ResultSet rs = Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"STT", "Mã Nhân Viên", "Họ Nhân Viên ", "Tên Nhân viên", "Giới tính", "Ngày Sinh", "Địa Chỉ","Điện Thoại","Email","Chức vụ"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblNhanVien_NhanVien.setModel(tableModel);
        int c = 0;
        try {
            while (rs.next()) {
                Object[] item = new Object[10];
                c++;
                item[0] = c;
                item[1] = rs.getString("MANV");
                item[2] = rs.getString("HONV");
                item[3] = rs.getString("TENNV");
                item[4] = rs.getString("GIOITINHNV");
                item[5] = rs.getString("NGAYSINH");
                item[6] = rs.getString("DIACHINV");
                item[7] = rs.getString("DIENTHOAINV");
                item[8] = rs.getString("EMAILNV");
                item[9] = rs.getString("CHUCVU");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien_NhanVien = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblMaNV = new javax.swing.JLabel();
        lblHoNV = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        lblGioiTinhNV = new javax.swing.JLabel();
        lblDiaChiNV = new javax.swing.JLabel();
        lblDienThoaiNV = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtHoNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtGioiTinhNV = new javax.swing.JTextField();
        txtDiaChiNV = new javax.swing.JTextField();
        txtDienThoaiNV = new javax.swing.JTextField();
        txtEmailNV = new javax.swing.JTextField();
        txtChucVu = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RadMaNV = new javax.swing.JRadioButton();
        RadChucVu = new javax.swing.JRadioButton();
        txtTimKiemNV = new javax.swing.JTextField();
        btnTimNV = new javax.swing.JButton();

        jPanel1.setToolTipText("Tìm Kiếm");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("DANH SÁCH NHÂN VIÊN ");

        tblNhanVien_NhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblNhanVien_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "Điện Thoai", "Email", "Chức Vụ"
            }
        ));
        tblNhanVien_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVien_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien_NhanVien);

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThem.setForeground(new java.awt.Color(0, 102, 0));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSua.setForeground(new java.awt.Color(0, 102, 0));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(0, 102, 0));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 102, 0));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblMaNV.setText("Mã Nhân Viên ");

        lblHoNV.setText("Họ Nhân Viên ");

        lblTenNV.setText("Tên Nhân Viên ");

        lblGioiTinhNV.setText("Giới Tính ");

        lblDiaChiNV.setText("Địa Chỉ");

        lblDienThoaiNV.setText("Điện Thoại");

        lblEmail.setText("Email");

        lblChucVu.setText("Chức Vụ");

        lblNgaySinh.setText("Ngày Sinh");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("TÌM KIẾM");

        RadMaNV.setForeground(new java.awt.Color(0, 153, 0));
        RadMaNV.setText("Mã Nhân Viên");

        RadChucVu.setForeground(new java.awt.Color(0, 153, 0));
        RadChucVu.setText("Chức Vụ");

        btnTimNV.setText("Tìm");
        btnTimNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadMaNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(RadChucVu)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(txtTimKiemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnTimNV)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiemNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadMaNV)
                    .addComponent(RadChucVu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimNV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNV)
                            .addComponent(lblHoNV)
                            .addComponent(lblTenNV)
                            .addComponent(lblGioiTinhNV)
                            .addComponent(lblNgaySinh))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txtHoNV)
                            .addComponent(txtMaNV)
                            .addComponent(txtTenNV)
                            .addComponent(txtGioiTinhNV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btnSua)
                        .addGap(69, 69, 69)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnXoa)
                        .addGap(73, 73, 73)
                        .addComponent(btnReset)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDienThoaiNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiaChiNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiaChiNV, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(txtDienThoaiNV)
                            .addComponent(txtEmailNV)
                            .addComponent(txtChucVu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNV)
                            .addComponent(lblDiaChiNV)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChiNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoNV)
                            .addComponent(lblDienThoaiNV)
                            .addComponent(txtHoNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDienThoaiNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenNV)
                            .addComponent(lblEmail)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioiTinhNV)
                            .addComponent(lblChucVu)
                            .addComponent(txtGioiTinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgaySinh)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnReset))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean KiemTraNhapNhanVien(int ts) {
        boolean kiemtra = false;
         String MaNV,HoNV,TenNV,GioiTinhNV,NgaySinh,DiaChiNV,DienThoaiNV,EmailNV,ChucVu;
        MaNV=txtMaNV.getText();
        HoNV=txtHoNV.getText();
        TenNV=txtTenNV.getText();
        GioiTinhNV=txtGioiTinhNV.getText();
        NgaySinh=txtNgaySinh.getText();
        DiaChiNV=txtDiaChiNV.getText();
        DienThoaiNV=txtDienThoaiNV.getText();
        EmailNV=txtEmailNV.getText();
        ChucVu= txtChucVu.getText();
        String  ThongBao = "";
        
        if (MaNV.equals("") && ts == 1) {
            ThongBao += "Bạn Chưa Nhập mã nhân viên\n";
            lblMaNV.setForeground(Color.red);
        }
        if (HoNV.equals("")) {
            ThongBao += "Bạn chưa Nhập Họ Nhân Viên\n";
            lblHoNV.setForeground(Color.red);
            
        }
        if (TenNV.equals("")) {
            ThongBao += "Bạn chưa Nhập Tên Nhân Viên\n";
            lblTenNV.setForeground(Color.red);
        }
        if (GioiTinhNV.equals("")) {
            lblGioiTinhNV.setForeground(Color.red);
            ThongBao += "Bạn chưa Nhập Giới tính nhân viên\n";
        }
        if (NgaySinh.equals("")) {
            lblNgaySinh.setForeground(Color.red);
            ThongBao += "Bạn chưa Nhập ngày sinh \n";
           
        }
        if (DiaChiNV.equals("")) {
            ThongBao += "Bạn chưa Nhập Địa Chỉ Nhân Viên\n";
            lblDiaChiNV.setForeground(Color.red);
        }
        if (DienThoaiNV.equals("")) {
            ThongBao += "Bạn chưa Nhập sdt Nhân Viên\n";
            lblDienThoaiNV.setForeground(Color.red);
        }
        if (EmailNV.equals("")) {
            ThongBao += "Bạn chưa Nhập Email Nhân Viên\n";
            lblEmail.setForeground(Color.red);
        }
        if (ChucVu.equals("")) {
            ThongBao += "Bạn chưa Nhập Chức Vụ Nhân Viên\n";
            lblChucVu.setForeground(Color.red);
        }
        if (ThongBao.equals("")) {
            kiemtra = true;
            lblMaNV.setForeground(Color.black);
            lblHoNV.setForeground(Color.black);
            lblTenNV.setForeground(Color.black);
            lblGioiTinhNV.setForeground(Color.black);
            lblNgaySinh.setForeground(Color.black);
            lblDiaChiNV.setForeground(Color.black);
            lblChucVu.setForeground(Color.black);
        } else {
            kiemtra = false;
            frmTC.ThongBao(ThongBao, "LỖI NHẬP LIỆU", 2);
        }
        return kiemtra;
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String MaNV,HoNV,TenNV,GioiTinhNV,NgaySinh,DiaChiNV,DienThoaiNV,EmailNV,ChucVu;
        MaNV=txtMaNV.getText();
        HoNV=txtHoNV.getText();
        TenNV=txtTenNV.getText();
        GioiTinhNV=txtGioiTinhNV.getText();
        NgaySinh=txtNgaySinh.getText();
        DiaChiNV=txtDiaChiNV.getText();
        DienThoaiNV=txtDienThoaiNV.getText();
        EmailNV=txtEmailNV.getText();
        ChucVu=txtChucVu.getText();
        String cautruyvan = "INSERT into NHANVIEN(MANV,HONV,TENNV,GIOITINHNV,NGAYSINH,DIACHINV,DIENTHOAINV,EMAILNV,CHUCVU) Values('" + MaNV + "',N'" + HoNV + "',N'" + TenNV + "',N'" + GioiTinhNV + "',Convert(datetime,'" + NgaySinh + "'),N'" + DiaChiNV + "','" + DienThoaiNV + "','" + EmailNV + "',N'" + ChucVu + "')";
        
        boolean kiemtra = KiemTraNhapNhanVien(0);
        if (kiemtra) {
            Main.connection.ExcuteQueryUpdateDB(cautruyvan);
            Main.frmTC.infoBox(" Thêm Thành Công !!!", "Thông báo");
            System.out.println("Đã Thêm Thành Công");
            System.out.println(cautruyvan);
        } else {
            System.out.println("Thất Bại");
        }
        LaydulieuNhanVien();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblNhanVien_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVien_NhanVienMouseClicked
        // TODO add your handling code here:
        int viTriDongVuaBam = tblNhanVien_NhanVien.getSelectedRow();
        txtMaNV.setText(tblNhanVien_NhanVien.getValueAt(viTriDongVuaBam, 1).toString());
        txtHoNV.setText(tblNhanVien_NhanVien.getValueAt(viTriDongVuaBam, 2).toString());
        txtTenNV.setText(tblNhanVien_NhanVien.getValueAt(viTriDongVuaBam, 3).toString());
        txtGioiTinhNV.setText(tblNhanVien_NhanVien.getValueAt(viTriDongVuaBam, 4).toString());
        txtNgaySinh.setText(tblNhanVien_NhanVien.getValueAt(viTriDongVuaBam, 5).toString());
        txtDiaChiNV.setText(tblNhanVien_NhanVien.getValueAt(viTriDongVuaBam, 6).toString());
        txtDienThoaiNV.setText(tblNhanVien_NhanVien.getValueAt(viTriDongVuaBam, 7).toString());
        txtEmailNV.setText(tblNhanVien_NhanVien.getValueAt(viTriDongVuaBam, 8).toString());
        txtChucVu.setText(tblNhanVien_NhanVien.getValueAt(viTriDongVuaBam, 9).toString());
        
    }//GEN-LAST:event_tblNhanVien_NhanVienMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String MaNV,HoNV,TenNV,GioiTinhNV,NgaySinh,DiaChiNV,DienThoaiNV,EmailNV,ChucVu;
        MaNV=txtMaNV.getText();
        HoNV=txtHoNV.getText();
        TenNV=txtTenNV.getText();
        GioiTinhNV=txtGioiTinhNV.getText();
        NgaySinh=txtNgaySinh.getText();
        DiaChiNV=txtDiaChiNV.getText();
        DienThoaiNV=txtDienThoaiNV.getText();
        EmailNV=txtEmailNV.getText();
        ChucVu=txtChucVu.getText();
        String cautruyvan = "update NHANVIEN set TENNV = N'" + TenNV +
                "',HONV=N'" + HoNV + "',DIENTHOAINV='" + DienThoaiNV + "',DIACHINV=N'" + DiaChiNV+"',CHUCVU=N'" + ChucVu + "',EMAILNV='" + EmailNV + "',GIOITINHNV=N'" + GioiTinhNV + "',NGAYSINH='" + NgaySinh + "' WHERE MANV='" + MaNV + "';";
        boolean kiemtra = KiemTraNhapNhanVien(0);
        if (kiemtra) {
            Main.connection.ExcuteQueryUpdateDB(cautruyvan);
            Main.frmTC.infoBox(" Sửa Thành Công !!!", "Thông báo");
            System.out.println("Đã Sửa Thành Công");
            System.out.println(cautruyvan);
        } else {
            System.out.println("Thất Bại");
        }
        LaydulieuNhanVien();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String MaNV = txtMaNV.getText();
        String cautruyvan = "delete NHANVIEN where MANV='" + MaNV+"';";
        // Main.frmTC.infoBox("  Lỗi  !!!", "Thông báo");
         //boolean kiemtra = KiemTraNhapNhanVien(0);
        if (txtMaNV.equals("")) {
           Main.frmTC.infoBox("  Lỗi  !!!", "Thông báo");
        } else {
            Main.connection.ExcuteQueryUpdateDB(cautruyvan);
            System.out.println("Đã Xóa Thành Công");
            Main.frmTC.infoBox("Xóa Thành Công !!!", "Thông báo");
            System.out.println(cautruyvan);
        }
        LaydulieuNhanVien();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
       txtMaNV.setText("");
       txtHoNV.setText("");
       txtTenNV.setText("");
       txtGioiTinhNV.setText("");
       txtNgaySinh.setText("");
       txtDiaChiNV.setText("");
        txtDienThoaiNV.setText("");
        txtEmailNV.setText("");
        txtChucVu.setText("");
        LaydulieuNhanVien();
        Main.frmTC.infoBox("  Reset thành công  !!!", "Thông báo");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTimNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimNVActionPerformed
        // TODO add your handling code here:
        TimKiemNV();
    }//GEN-LAST:event_btnTimNVActionPerformed
 public void TimKiemNV()
 {
      String Tim = "";
        if (RadMaNV.isSelected())
        {
            Tim= txtTimKiemNV.getText();
            String cautruyvan = "";
        cautruyvan = "select * from NHANVIEN where MANV= '" +Tim+"'";
        ResultSet rs = Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"STT", "Mã Nhân Viên", "Họ Nhân Viên ", "Tên Nhân viên", "Giới tính", "Ngày Sinh", "Địa Chỉ","Điện Thoại","Email","Chức vụ"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblNhanVien_NhanVien.setModel(tableModel);
        int c = 0;
        try {
            while (rs.next()) {
                Object[] item = new Object[10];
                c++;
                item[0] = c;
                item[1] = rs.getString("MANV");
                item[2] = rs.getString("HONV");
                item[3] = rs.getString("TENNV");
                item[4] = rs.getString("GIOITINHNV");
                item[5] = rs.getString("NGAYSINH");
                item[6] = rs.getString("DIACHINV");
                item[7] = rs.getString("DIENTHOAINV");
                item[8] = rs.getString("EMAILNV");
                item[9] = rs.getString("CHUCVU");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
            
        } else if (RadChucVu.isSelected()){

       String cautruyvan = "";
        cautruyvan = "select * from NHANVIEN where CHUCVU like N'"+txtTimKiemNV.getText().trim()+"'";
         
        ResultSet rs = Main.connection.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"STT", "Mã Nhân Viên", "Họ Nhân Viên ", "Tên Nhân viên", "Giới tính", "Ngày Sinh", "Địa Chỉ","Điện Thoại","Email","Chức vụ"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblNhanVien_NhanVien.setModel(tableModel);
        int c = 0;
        System.out.println(cautruyvan);
        try {
            while (rs.next()) {
                Object[] item = new Object[10];
                c++;
                item[0] = c;
                item[1] = rs.getString("MANV");
                item[2] = rs.getString("HONV");
                item[3] = rs.getString("TENNV");
                item[4] = rs.getString("GIOITINHNV");
                item[5] = rs.getString("NGAYSINH");
                item[6] = rs.getString("DIACHINV");
                item[7] = rs.getString("DIENTHOAINV");
                item[8] = rs.getString("EMAILNV");
                item[9] = rs.getString("CHUCVU");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        }
 }
         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadChucVu;
    private javax.swing.JRadioButton RadMaNV;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimNV;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblDiaChiNV;
    private javax.swing.JLabel lblDienThoaiNV;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinhNV;
    private javax.swing.JLabel lblHoNV;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JTable tblNhanVien_NhanVien;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtDiaChiNV;
    private javax.swing.JTextField txtDienThoaiNV;
    private javax.swing.JTextField txtEmailNV;
    private javax.swing.JTextField txtGioiTinhNV;
    private javax.swing.JTextField txtHoNV;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTimKiemNV;
    // End of variables declaration//GEN-END:variables
}
