/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import KFC.Main;
import database.clsConnectDB;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class ThongKeJPanel extends javax.swing.JPanel {
    public static clsConnectDB con;
    /**
     * Creates new form ThongKeJPanel
     */
    public ThongKeJPanel() {
        initComponents();
         con = new clsConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnReportKhachHang = new javax.swing.JButton();
        btnReport1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNCC = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("DANH SÁCH BÁO CÁO");

        btnReportKhachHang.setText("REPORT");
        btnReportKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportKhachHangActionPerformed(evt);
            }
        });

        btnReport1.setText("REPORT");
        btnReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("I . THỐNG KÊ LƯỢNG HÓA ĐƠN CỦA CÁC KHÁCH HÀNG ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setText("II .THỐNG KÊ LƯỢNG HÓA ĐƠN CỦA MỖI NHÂN VIÊN LẬP NÊN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setText("III.THỐNG KÊ LƯỢNG HÀNG NHẬP TRONG QUÝ 1");

        btnNCC.setText("REPORT");
        btnNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReportKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(btnReport1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents



    private void btnReportKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportKhachHangActionPerformed
        // TODO add your handling code here:
        
    try {  
         HashMap map = new HashMap();
//String reportName = "src/Report/ReportKhachHang.jrxml";
  JasperDesign jd = JRXmlLoader.load("D:\\hoctap\\JAVA\\QuanLyBanHang\\src\\Report\\reportKhachHang.jrxml");
JasperReport jr = JasperCompileManager.compileReport("src/Report/reportKhachHang.jrxml");
JasperPrint jasperPrint = JasperFillManager.fillReport(jr, map, clsConnectDB.conn);
//JasperExportManager.exportReportToHtmlFile(jasperPrint, ".html");

JasperViewer.viewReport(jasperPrint, false);

} catch (JRException ex) {
System.out.println(ex.getMessage());
}


    }//GEN-LAST:event_btnReportKhachHangActionPerformed

    private void btnReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport1ActionPerformed
        // TODO add your handling code here:
        try {  
         HashMap map = new HashMap();
//String reportName = "src/Report/ReportKhachHang.jrxml";
  JasperDesign jd = JRXmlLoader.load("D:\\hoctap\\JAVA\\QuanLyBanHang\\src\\Report\\reportNhanVien.jrxml");
JasperReport jr = JasperCompileManager.compileReport("src/Report/reportNhanVien.jrxml");
JasperPrint jasperPrint = JasperFillManager.fillReport(jr, map, clsConnectDB.conn);
//JasperExportManager.exportReportToHtmlFile(jasperPrint, ".html");

JasperViewer.viewReport(jasperPrint, false);

} catch (JRException ex) {
System.out.println(ex.getMessage());
}
    }//GEN-LAST:event_btnReport1ActionPerformed

    private void btnNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCCActionPerformed
        // TODO add your handling code here:
                try {  
         HashMap map = new HashMap();
//String reportName = "src/Report/ReportKhachHang.jrxml";
  JasperDesign jd = JRXmlLoader.load("D:\\hoctap\\JAVA\\QuanLyBanHang\\src\\Report\\reportNhaCungCap.jrxml");
JasperReport jr = JasperCompileManager.compileReport("src/Report/reportNhaCungCap.jrxml");
JasperPrint jasperPrint = JasperFillManager.fillReport(jr, map, clsConnectDB.conn);
//JasperExportManager.exportReportToHtmlFile(jasperPrint, ".html");

JasperViewer.viewReport(jasperPrint, false);

} catch (JRException ex) {
System.out.println(ex.getMessage());
}
    }//GEN-LAST:event_btnNCCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNCC;
    private javax.swing.JButton btnReport1;
    private javax.swing.JButton btnReportKhachHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
